// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file


import 'dart:typed_data';
import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'match.dart';
import 'team.dart';
import 'team_member.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5574094097141227077),
    name: 'Team',
    lastPropertyId: const obx_int.IdUid(4, 3702111810584608286),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7480468375241954143),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5497173086096522060),
        name: 'teamId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6160706795430400873),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1009131259175838877),
        name: 'teamName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3702111810584608286),
        name: 'teamCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6275006849892722633),
    name: 'TeamMember',
    lastPropertyId: const obx_int.IdUid(4, 5224547398743552308),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5079742640710249772),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6393149296654824372),
        name: 'playerId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 4646022466543221506),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1614703684759733346),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5224547398743552308),
        name: 'teamName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2775877443378871095),
    name: 'Match',
    lastPropertyId: const obx_int.IdUid(8, 54153367472196813),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8124953642853590526),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7122228267786482968),
        name: 'matchId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 4379219791951689544),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 435300751899356130),
        name: 'teamId1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6487779178865299046),
        name: 'teamId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 720098033746807084),
        name: 'tossWonBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1996007448253744580),
        name: 'batBowlFlag',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6812028044889582585),
        name: 'noballFlag',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 54153367472196813),
        name: 'wideFlag',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 2775877443378871095),
    lastIndexId: const obx_int.IdUid(3, 4379219791951689544),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Team: obx_int.EntityDefinition<Team>(
      model: _entities[0],
      toOneRelations: (Team object) => [],
      toManyRelations: (Team object) => {},
      getId: (Team object) => object.id,
      setId: (Team object, int id) {
        object.id = id;
      },
      objectToFB: (Team object, fb.Builder fbb) {
        final teamIdOffset = fbb.writeString(object.teamId);
        final teamNameOffset = fbb.writeString(object.teamName);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, teamIdOffset);
        fbb.addOffset(2, teamNameOffset);
        fbb.addInt64(3, object.teamCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Team(
          id: idParam,
          teamId: teamIdParam,
          teamName: teamNameParam,
          teamCount: teamCountParam,
        );

        return object;
      },
    ),
    TeamMember: obx_int.EntityDefinition<TeamMember>(
      model: _entities[1],
      toOneRelations: (TeamMember object) => [],
      toManyRelations: (TeamMember object) => {},
      getId: (TeamMember object) => object.id,
      setId: (TeamMember object, int id) {
        object.id = id;
      },
      objectToFB: (TeamMember object, fb.Builder fbb) {
        final playerIdOffset = fbb.writeString(object.playerId);
        final teamIdOffset = fbb.writeString(object.teamId);
        final teamNameOffset = fbb.writeString(object.teamName);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, playerIdOffset);
        fbb.addOffset(2, teamIdOffset);
        fbb.addOffset(3, teamNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = TeamMember(
          id: idParam,
          playerId: playerIdParam,
          teamId: teamIdParam,
          teamName: teamNameParam,
        );

        return object;
      },
    ),
    Match: obx_int.EntityDefinition<Match>(
      model: _entities[2],
      toOneRelations: (Match object) => [],
      toManyRelations: (Match object) => {},
      getId: (Match object) => object.id,
      setId: (Match object, int id) {
        object.id = id;
      },
      objectToFB: (Match object, fb.Builder fbb) {
        final matchIdOffset = fbb.writeString(object.matchId);
        final teamId1Offset = fbb.writeString(object.teamId1);
        final teamId2Offset = fbb.writeString(object.teamId2);
        final tossWonByOffset = fbb.writeString(object.tossWonBy);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, matchIdOffset);
        fbb.addOffset(2, teamId1Offset);
        fbb.addOffset(3, teamId2Offset);
        fbb.addOffset(4, tossWonByOffset);
        fbb.addInt64(5, object.batBowlFlag);
        fbb.addInt64(6, object.noballFlag);
        fbb.addInt64(7, object.wideFlag);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final matchIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamId1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final tossWonByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final batBowlFlagParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final noballFlagParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final wideFlagParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = Match(
          id: idParam,
          matchId: matchIdParam,
          teamId1: teamId1Param,
          teamId2: teamId2Param,
          tossWonBy: tossWonByParam,
          batBowlFlag: batBowlFlagParam,
          noballFlag: noballFlagParam,
          wideFlag: wideFlagParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Team] entity fields to define ObjectBox queries.
class Team_ {
  /// See [Team.id].
  static final id = obx.QueryIntegerProperty<Team>(_entities[0].properties[0]);

  /// See [Team.teamId].
  static final teamId = obx.QueryStringProperty<Team>(
    _entities[0].properties[1],
  );

  /// See [Team.teamName].
  static final teamName = obx.QueryStringProperty<Team>(
    _entities[0].properties[2],
  );

  /// See [Team.teamCount].
  static final teamCount = obx.QueryIntegerProperty<Team>(
    _entities[0].properties[3],
  );
}

/// [TeamMember] entity fields to define ObjectBox queries.
class TeamMember_ {
  /// See [TeamMember.id].
  static final id = obx.QueryIntegerProperty<TeamMember>(
    _entities[1].properties[0],
  );

  /// See [TeamMember.playerId].
  static final playerId = obx.QueryStringProperty<TeamMember>(
    _entities[1].properties[1],
  );

  /// See [TeamMember.teamId].
  static final teamId = obx.QueryStringProperty<TeamMember>(
    _entities[1].properties[2],
  );

  /// See [TeamMember.teamName].
  static final teamName = obx.QueryStringProperty<TeamMember>(
    _entities[1].properties[3],
  );
}

/// [Match] entity fields to define ObjectBox queries.
class Match_ {
  /// See [Match.id].
  static final id = obx.QueryIntegerProperty<Match>(_entities[2].properties[0]);

  /// See [Match.matchId].
  static final matchId = obx.QueryStringProperty<Match>(
    _entities[2].properties[1],
  );

  /// See [Match.teamId1].
  static final teamId1 = obx.QueryStringProperty<Match>(
    _entities[2].properties[2],
  );

  /// See [Match.teamId2].
  static final teamId2 = obx.QueryStringProperty<Match>(
    _entities[2].properties[3],
  );

  /// See [Match.tossWonBy].
  static final tossWonBy = obx.QueryStringProperty<Match>(
    _entities[2].properties[4],
  );

  /// See [Match.batBowlFlag].
  static final batBowlFlag = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[5],
  );

  /// See [Match.noballFlag].
  static final noballFlag = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[6],
  );

  /// See [Match.wideFlag].
  static final wideFlag = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[7],
  );
}
